liste_1 = [
    "text",
    "lang",
    "quote_count",
    "reply_count",
    "retweet_count",
    "favorite_count",
    ["user", "id"],
    ["user", "name"],
    ["user", "screen_name"],
    ["user", "location"],
    ["user", "description"],
    ["user", "protected"],
    ["user", "verified"],
    ["user", "followers_count"],
    ["user", "friends_count"],
    ["user", "listed_count"],
    ["user", "favourites_count"],
    ["user", "statuses_count"],
    ["user", "created_at"],
    # ["user", "utc_offset"], # tjrs null
    # ["user", "time_zone"], # tjrs null
    ["user", "contributors_enabled"],
    ["user", "geo_enabled"],
    ["user", "profile_background_color"],
    ["user", "profile_sidebar_border_color"],
    ["user", "profile_sidebar_fill_color"],
    ["user", "profile_text_color"],
    ["user", "profile_use_background_image"],
    ["user", "default_profile"],
    # ["user", "lang"],
    # ["user", "following"],
    # ["user", "follow_request_sent"],
    # ["user", "notifications"],
    ["user", "description"],
    ["place", "name"],
    ["place", "full_name"],
    ["place", "place_type"],
    ["place", "country_code"],
    ["place", "country"],
    ["place", "bounding_box"],  # À enlever après vérification
    ["place", "bounding_box", "type"],
    ["place", "bounding_box", "coordinates"],
    # "entities",
]

