"""Listes des variables à garder"""

# Liste 1 (celle par défaut, courte)
liste_1 = [
    ["text"],
    ["extended_tweet", "full_text"],
    ["lang"],
    ["retweeted_status", "user", "screen_name"],
    ["retweeted_status", "text"],
    ["retweeted_status", "extended_tweet", "full_text"],
    # ["quote_count"], # =0 pour tous (à récupérer) et juste pour pondérer
    # ["reply_count"],
    # ["retweet_count"],
    # ["favorite_count"],
    ["user", "id"],
    ["user", "name"],
    ["user", "screen_name"],
    ["user", "location"],
    ["user", "description"],
    ["user", "followers_count"],
    ["user", "friends_count"],
    ["user", "listed_count"],
    ["user", "favourites_count"],
    ["user", "statuses_count"],
    # ["user", "created_at"],
    # ["user", "profile_background_color"], Inutilisés
    # ["user", "profile_sidebar_border_color"],
    # ["user", "profile_sidebar_fill_color"],
    # ["user", "profile_text_color"],
    # ["user", "profile_use_background_image"],
    # ["user", "default_profile"],
    ["place", "name"],
    ["place", "full_name"],
    ["place", "place_type"],
    ["place", "country_code"],
    ["place", "country"],
    ["place", "bounding_box", "type"],
    ["place", "bounding_box", "coordinates"],
    # ["place", "bounding_box"],  # À enlever après vérification
    # ["entities"], # Inutiles
    # ["quoted_status", "extended_tweet", "full_text"],
    # ["quoted_status", "text"],
    # ["user", "protected"],
    # ["user", "verified"],
    # ["user", "contributors_enabled"],
    # ["user", "geo_enabled"],
    # ["user", "utc_offset"], # Tjrs null
    # ["user", "time_zone"],
    # ["user", "lang"],
    # ["user", "following"],
    # ["user", "follow_request_sent"],
    # ["user", "notifications"],
]


# Liste 2 (plus longue)
liste_2 = [
    ["text"],
    ["extended_tweet", "full_text"],
    ["lang"],
    ["retweeted_status", "user", "screen_name"],
    ["retweeted_status", "text"],
    ["retweeted_status", "extended_tweet", "full_text"],
    # ["quote_count"], # =0 pour tous et juste pour pondérer
    # ["reply_count"],
    # ["retweet_count"],
    # ["favorite_count"],
    ["user", "id"],
    ["user", "name"],
    ["user", "screen_name"],
    ["user", "location"],
    ["user", "description"],
    ["user", "followers_count"],
    ["user", "friends_count"],
    ["user", "listed_count"],
    ["user", "favourites_count"],
    ["user", "statuses_count"],
    ["user", "created_at"],
    ["user", "profile_background_color"],
    ["user", "profile_sidebar_border_color"],
    ["user", "profile_sidebar_fill_color"],
    ["user", "profile_text_color"],
    ["user", "profile_use_background_image"],
    ["user", "default_profile"],
    ["place", "name"],
    ["place", "full_name"],
    ["place", "place_type"],
    ["place", "country_code"],
    ["place", "country"],
    ["place", "bounding_box", "type"],
    ["place", "bounding_box", "coordinates"],
    ["entities"],
    ["user", "protected"],
    ["user", "verified"],
    ["user", "contributors_enabled"],
    ["user", "geo_enabled"],
]
