# See details on : https://github.com/marketplace/actions/github-push and https://github.community/t/run-job-only-if-folder-changed/118292/8

name: Project Documentation

on:
  push:
    branches: [master]

jobs:
  docs:
    name: Build the doc
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install pdoc3
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate documentation
        run: |
          pdoc --html -f --output-dir docs projet_python_twitter
          mv docs/projet_python_twitter/* docs
          rmdir docs/projet_python_twitter

  check:
    name: Check files

    needs: docs

    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}

    runs-on: ubuntu-latest

    steps:
      - name: check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file != docs/* ]]; then
              echo "This modified file is not under the 'docs' folder."
              echo "::set-output name=run_job::false"
              break
            else
              echo "::set-output name=run_job::true"
            fi
          done < files.txt

  commit:
    name: Commit if changed

    needs: check

    runs-on: ubuntu-latest

    if: needs.check.outputs.run_job == 'true'

    steps:
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update documentation automatically" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
